import React from "react";
import { useParams, useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import { Brain, Database, Bot, Shield, ArrowLeft, CheckCircle } from "lucide-react";

const featureData = {
  "ai-chat-assistant": {
    icon: Brain,
    title: "AI Chat Assistant",
    tagline: "Ask questions, get instant answers from your documents.",
    description:
      "Our AI Chat Assistant uses large language models combined with your uploaded documents to deliver precise, context-aware answers. No more digging through folders — just ask.",
    highlights: [
      "Natural language question answering",
      "Context-aware multi-turn conversations",
      "Cites source documents in responses",
      "Supports PDF and text documents",
      "Powered by Groq's llama-3.1-8b-instant model",
    ],
    color: "from-indigo-500 to-purple-600",
    bg: "bg-indigo-600/10",
    border: "border-indigo-500/30",
  },
  "vector-search": {
    icon: Database,
    title: "Vector Search",
    tagline: "Find meaning, not just keywords.",
    description:
      "Traditional search matches keywords. Vector search understands meaning. Using embeddings generated by all-MiniLM-L6-v2, every document chunk is stored as a high-dimensional vector and retrieved by semantic similarity.",
    highlights: [
      "Semantic similarity search",
      "Embedding via all-MiniLM-L6-v2",
      "MongoDB Atlas vector index",
      "Top-5 relevant chunks retrieved per query",
      "Works across large document collections",
    ],
    color: "from-cyan-500 to-blue-600",
    bg: "bg-cyan-600/10",
    border: "border-cyan-500/30",
  },
  "automation-engine": {
    icon: Bot,
    title: "Automation Engine",
    tagline: "Let AI handle the repetitive work.",
    description:
      "The Automation Engine lets you define workflows that automatically extract, summarize, and act on information from your documents — saving hours of manual effort.",
    highlights: [
      "Automated document processing pipelines",
      "Data extraction from uploaded files",
      "Workflow triggers on document upload",
      "Result storage and retrieval",
      "Extensible automation model",
    ],
    color: "from-emerald-500 to-teal-600",
    bg: "bg-emerald-600/10",
    border: "border-emerald-500/30",
  },
  "enterprise-security": {
    icon: Shield,
    title: "Enterprise Security",
    tagline: "Your data stays yours.",
    description:
      "Every request is authenticated with JWT tokens. Documents are scoped per user — no cross-user data leakage. Passwords are bcrypt-hashed and never stored in plain text.",
    highlights: [
      "JWT-based authentication",
      "Per-user document isolation",
      "bcrypt password hashing",
      "Protected API routes via middleware",
      "Google OAuth support",
    ],
    color: "from-rose-500 to-pink-600",
    bg: "bg-rose-600/10",
    border: "border-rose-500/30",
  },
};

const FeatureDetail = () => {
  const { slug } = useParams();
  const navigate = useNavigate();
  const feature = featureData[slug];

  if (!feature) {
    return (
      <div className="min-h-screen bg-slate-950 text-white flex items-center justify-center">
        <div className="text-center">
          <p className="text-slate-400 mb-4">Feature not found.</p>
          <button onClick={() => navigate("/features")} className="text-indigo-400 hover:underline">
            ← Back to Features
          </button>
        </div>
      </div>
    );
  }

  const Icon = feature.icon;

  return (
    <div className="min-h-screen bg-slate-950 text-white px-6 py-24">
      <div className="max-w-3xl mx-auto">

        {/* Back */}
        <button
          onClick={() => navigate("/features")}
          className="flex items-center gap-2 text-slate-400 hover:text-white mb-10 transition"
        >
          <ArrowLeft size={18} /> Back to Features
        </button>

        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <div className={`w-16 h-16 rounded-xl ${feature.bg} flex items-center justify-center mb-6`}>
            <Icon size={32} className="text-white" />
          </div>

          <h1 className={`text-4xl font-bold mb-3 bg-gradient-to-r ${feature.color} bg-clip-text text-transparent`}>
            {feature.title}
          </h1>

          <p className="text-slate-300 text-lg mb-6">{feature.tagline}</p>

          <p className="text-slate-400 leading-relaxed mb-10">{feature.description}</p>
        </motion.div>

        {/* Highlights */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.2 }}
          className={`bg-slate-900 border ${feature.border} rounded-xl p-6`}
        >
          <h2 className="text-lg font-semibold mb-4">What's included</h2>
          <ul className="space-y-3">
            {feature.highlights.map((point, i) => (
              <li key={i} className="flex items-start gap-3 text-slate-300 text-sm">
                <CheckCircle size={18} className="text-indigo-400 mt-0.5 shrink-0" />
                {point}
              </li>
            ))}
          </ul>
        </motion.div>

        {/* CTA */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.4 }}
          className="mt-10"
        >
          <button
            onClick={() => navigate("/chat")}
            className={`px-6 py-3 rounded-lg bg-gradient-to-r ${feature.color} text-white font-semibold shadow-lg hover:opacity-90 transition`}
          >
            Try it in Workspace →
          </button>
        </motion.div>

      </div>
    </div>
  );
};

export default FeatureDetail;
